// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlINgFMEUatA6kQJnF4QDS8ep8S4Kvksk',
    appId: '1:317415672220:web:52dfdec0fc3988e2536059',
    messagingSenderId: '317415672220',
    projectId: 'bountyhunt-c5d0d',
    authDomain: 'bountyhunt-c5d0d.firebaseapp.com',
    storageBucket: 'bountyhunt-c5d0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgX6kgf4YfiE021X-jzMcN4_H_o-oCFPo',
    appId: '1:317415672220:android:2cf6507ee8613284536059',
    messagingSenderId: '317415672220',
    projectId: 'bountyhunt-c5d0d',
    storageBucket: 'bountyhunt-c5d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-YVaHA7w9CSIy3F4woNQwyJgAD5rTxw',
    appId: '1:317415672220:ios:8de1df8193a103ca536059',
    messagingSenderId: '317415672220',
    projectId: 'bountyhunt-c5d0d',
    storageBucket: 'bountyhunt-c5d0d.appspot.com',
    iosBundleId: 'com.example.freelanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt-YVaHA7w9CSIy3F4woNQwyJgAD5rTxw',
    appId: '1:317415672220:ios:8de1df8193a103ca536059',
    messagingSenderId: '317415672220',
    projectId: 'bountyhunt-c5d0d',
    storageBucket: 'bountyhunt-c5d0d.appspot.com',
    iosBundleId: 'com.example.freelanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlINgFMEUatA6kQJnF4QDS8ep8S4Kvksk',
    appId: '1:317415672220:web:25f77e67cef0ab82536059',
    messagingSenderId: '317415672220',
    projectId: 'bountyhunt-c5d0d',
    authDomain: 'bountyhunt-c5d0d.firebaseapp.com',
    storageBucket: 'bountyhunt-c5d0d.appspot.com',
  );
}
